### ISSUE TITLE
Errors Encountered When Importing RAML Fragments

### ISSUE THREAD

**Issue by AnilProlifics** [jonathanfiss/common-raml-fragment#1]
When following the instructions to import the RAML fragments, I noticed that `securities-raml-fragment` is being referred to in the following resource types:

- `experience-resourcetypes.raml`
- `process-resourcetypes.raml`
- `system-resourcetypes.raml`

Upon importing, the following errors can be seen in the Design Center:

exchange.json (1:1) | `Error: Asset /securities-raml-fragment/1.0.0/ is unreachable`

resourcetypes/experience-resourcetypes.raml (5:13) | `Error: Resource /resourcetypes/exchange_modules/ebd9d6f2-2413-467f-85d4-803be06dd391/securities-raml-fragment/1.0.0/securities-raml-fragment.raml not found`

resourcetypes/process-resourcetypes.raml (5:13) | `Error: Resource /resourcetypes/exchange_modules/ebd9d6f2-2413-467f-85d4-803be06dd391/securities-raml-fragment/1.0.0/securities-raml-fragment.raml not found`

resourcetypes/system-resourcetypes.raml (5:13) | `Error: Resource /resourcetypes/exchange_modules/ebd9d6f2-2413-467f-85d4-803be06dd391/securities-raml-fragment/1.0.0/securities-raml-fragment.raml not found`

It seems `securities-raml-fragment` is part of another fragment.

Thanks.

**Comment by AnilProlifics** [comment]
I have found it at https://github.com/jonathanfiss/securities-raml-fragment which I'll import first before common-raml-fragment. Thanks.

**Comment by jonathanfiss** [comment]
Thank you @AnilProlifics for your observation. I will improve the Readme and add the reference to this other fragment.
